# Machine type
MACHINE = generic

# CPU type
PROCESSOR = sun4v

# Support for SMP
CONFIG_SMP = n

# Framebuffer support
CONFIG_FB = n

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
