# Machine type
MACHINE = generic

# CPU type
PROCESSOR = sun4v

# Quad Floats
QUADFLOAT = hard

# Support for SMP
CONFIG_SMP = n

# Framebuffer support
CONFIG_FB = n

# Dynamic linking support
CONFIG_RTLD = y

# Build shared libraries
CONFIG_BUILD_SHARED_LIBS = y

# Link against shared libraries
CONFIG_USE_SHARED_LIBS = y

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
