# Platform
PLATFORM = ia32

# CPU type
PROCESSOR = pentium4

# Ramdisk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# In case compiler is clang, whether or not to use its integrated assembler.
INTEGRATED_AS = default

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# ACPI support
CONFIG_ACPI = y

# Support for SMP
CONFIG_SMP = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# PC keyboard support
CONFIG_PC_KBD = y

# EGA support
CONFIG_EGA = y

# Framebuffer support
CONFIG_FB = y

# Default framebuffer mode
CONFIG_BFB_MODE = 1024x768

# Default framebuffer depth
CONFIG_BFB_BPP = 16

# Dynamic linking support
CONFIG_RTLD = y

# Build shared libraries
CONFIG_BUILD_SHARED_LIBS = y

# Link against shared libraries
CONFIG_USE_SHARED_LIBS = y

# Include userspace unit tests (PCUT)
CONFIG_PCUT_TESTS = y

# Include development files (headers, libraries)
CONFIG_DEVEL_FILES = y

# OHCI root hub power switch, ganged is enough
OHCI_POWER_SWITCH = ganged

# GRUB boot loader architecture
GRUB_ARCH = pc

# Optimization level
OPTIMIZATION = 3
