# Platform
PLATFORM = ia64

# Machine type
MACHINE = i460GX

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for SMP
CONFIG_SMP = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Use VHPT
CONFIG_VHPT = n

# Support for NS16550 serial port
CONFIG_NS16550 = y

# IOSapic on default address support
CONFIG_IOSAPIC = y

# Interrupt-driven driver for NS16550?
CONFIG_NS16550_INTERRUPT_DRIVEN = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Compile kernel tests
CONFIG_TEST = y
