# Machine type
MACHINE = leon3

# CPU type
PROCESSOR = leon3

# Barebone build with essential binaries only
CONFIG_BAREBONE = y

# GRLIB APBUART
CONFIG_GRLIB_UART = y

# GRLIB IRQMP
CONFIG_GRLIB_IRQMP = y
