# Machine type
MACHINE = generic

# CPU type
PROCESSOR = us

# Quad Floats
QUADFLOAT = hard

# Dynamic linking support
CONFIG_RTLD = y

# Build shared libraries
CONFIG_BUILD_SHARED_LIBS = y

# Link against shared libraries
CONFIG_USE_SHARED_LIBS = y

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
