# Machine type
MACHINE = gta02

# RAM disk format
RDFMT = tmpfs

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Compile kernel tests
CONFIG_TEST = n

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
