# Machine type
MACHINE = gta02

# RAM disk format
RDFMT = tmpfs

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = n

# Kernel symbol information
CONFIG_SYMTAB = n

# Compile kernel tests
CONFIG_TEST = n

# Framebuffer support
CONFIG_FB = n

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
