# Platform
PLATFORM = ppc64

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y
