## General configuration directives
#
# CONFIG_SMP (n/y)
#       Support for symetric multiprocessors
#
# CONFIG_HT (n/y)
#       Improved support for hyperthreading
#
# CONFIG_FPU_LAZY (n/y)
#       Lazy context switching
#

CONFIG_SMP = y
CONFIG_HT = y
CONFIG_FPU_LAZY = y

## Debugging configuration directives
#
# CONFIG_DEBUG (n/y)
#       General debuging and assert checking
#
# CONFIG_DEBUG_SPINLOCK (n/y)
#       Deadlock detection support for spinlocks
#

CONFIG_DEBUG = n
CONFIG_DEBUG_SPINLOCK = y

## Run-time configuration directives
#
# CONFIG_USERSPACE (n/y)
#       Enable user space support
#
# CONFIG_TEST (value)
#       Compile in test "value" (empty string for no test)
#

CONFIG_USERSPACE = n
CONFIG_TEST =
#CONFIG_TEST = synch/rwlock1
#CONFIG_TEST = synch/rwlock2
#CONFIG_TEST = synch/rwlock3
#CONFIG_TEST = synch/rwlock4
#CONFIG_TEST = synch/rwlock5
#CONFIG_TEST = synch/semaphore1
#CONFIG_TEST = synch/semaphore2
#CONFIG_TEST = fpu/fpu1
#CONFIG_TEST = fpu/sse1
#CONFIG_TEST = fpu/mips1
#CONFIG_TEST = print/print1
#CONFIG_TEST = thread/thread1
#CONFIG_TEST = mm/mapping1
