## General configuration directives
#
# CONFIG_SMP (n/y)
#       Support for symetric multiprocessors
#
# CONFIG_HT (n/y)
#       Improved support for hyperthreading
#
# CONFIG_FPU_LAZY (n/y)
#       Lazy context switching
#

CONFIG_SMP = y
CONFIG_HT = y
CONFIG_FPU_LAZY = y

## Debugging configuration directives
#
# CONFIG_DEBUG (n/y)
#       General debuging and assert checking
#
# CONFIG_DEBUG_SPINLOCK (n/y)
#       Deadlock detection support for spinlocks
#

CONFIG_DEBUG = n
CONFIG_DEBUG_SPINLOCK = y
