# Platform
PLATFORM = ppc32

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# Framebuffer support
CONFIG_FB = y

# Load disk drivers on startup
CONFIG_START_BD = n

# Mount /data on startup
CONFIG_MOUNT_DATA = n

# OHCI root hub power switch, ganged is enough
OHCI_POWER_SWITCH = ganged

