# Platform
PLATFORM = ppc32

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = keyboard

# Output device class
CONFIG_HID_OUT = monitor

# Framebuffer support
CONFIG_FB = y

# Use Block Address Translation by the loader
CONFIG_BAT = y

# Keyboard layout
KBD_LAYOUT = us_qwerty
