# Platform
PLATFORM = ppc32

# Ramdisk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# In case compiler is clang, whether or not to use its integrated assembler.
INTEGRATED_AS = default

# Lazy FPU context switching
CONFIG_FPU_LAZY = n

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# Framebuffer support
CONFIG_FB = y

# Dynamic linking support
CONFIG_RTLD = y

# Build shared libraries
CONFIG_BUILD_SHARED_LIBS = y

# Link against shared libraries
CONFIG_USE_SHARED_LIBS = y

# OHCI root hub power switch, ganged is enough
OHCI_POWER_SWITCH = ganged

# Optimization level
OPTIMIZATION = 3
