# Platform
PLATFORM = sparc64

# CPU type
MACHINE = us

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for SMP
CONFIG_SMP = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Use TSB
CONFIG_TSB = y

# Support for Z8530 serial port
CONFIG_Z8530 = y

# Support for NS16550 serial port
CONFIG_NS16550 = y

# Support for Serengeti console
CONFIG_SGCN = y

# Interrupt-driven driver for NS16550?
CONFIG_NS16550_INTERRUPT_DRIVEN = y

# Virtually indexed D-cache support
CONFIG_VIRT_IDX_DCACHE = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Compile kernel tests
CONFIG_TEST = y

# Start AP processors by the loader
CONFIG_SMP = y

# Preserve A.OUT header in isofs.b
CONFIG_AOUT_ISOFS_B = y

# External ramdisk
CONFIG_RD_EXTERNAL = n
