# Platform
PLATFORM = mips32

# Machine type
MACHINE = lgxemul

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Save all interrupt registers
CONFIG_DEBUG_ALLREGS = y

# Compile kernel tests
CONFIG_TEST = y

# Framebuffer support
CONFIG_FB = y
