/* Automatically generated by mknewcmd on Don Nov 29 19:01:45 CET 2018
 * This is machine generated output. The author of mknewcmd claims no
 * copyright over the contents of this file. Where legally permitted, the
 * contents herein are donated to the public domain.
 *
 * You should apply any license and copyright that you wish to this file,
 * replacing this header in its entirety. */

#include <stdio.h>
#include <stdlib.h>
#include <str.h>
#include "config.h"
#include "util.h"
#include "errors.h"
#include "entry.h"
#include "alias.h"
#include "cmds.h"

#include <adt/odict.h>


static const char *cmdname = "alias";
static const char* alias_format = "%s/%s";


/*
#include <types/adt/odict.h>
extern void odict_initialize(odict_t *, odgetkey_t, odcmp_t);
extern void odict_finalize(odict_t *);
extern void odlink_initialize(odlink_t *);
extern void odict_insert(odlink_t *, odict_t *, odlink_t *);
extern void odict_remove(odlink_t *);

extern odlink_t *odict_first(odict_t *);
extern odlink_t *odict_next(odlink_t *, odict_t *);
extern odlink_t *odict_find_eq(odict_t *, void *, odlink_t *);
extern errno_t odict_validate(odict_t *);
*/


static void list_aliases()
{
	odlink_t *alias_link = odict_first(&alias_dict);
	while (alias_link != NULL) {
		alias_t *data = odict_get_instance(alias_link, alias_t, odict);

		printf(alias_format, data->name, data->value);

		alias_link = odict_next(alias_link, &alias_dict);
	}
}

static int print_alias(const char* name)
{
	odlink_t *alias_link = odict_find_eq(&alias_dict, (void*)name, NULL);
	if (alias_link != NULL) {
		alias_t* data = odict_get_instance(alias_link, alias_t, odict);
		printf(alias_format, data->name, data->value);
		return CMD_SUCCESS;
	}



	printf("No alias with the name '%s' exists", name);
	return CMD_FAILURE;
}

static void set_alias(const char* name, const char* value)
{
	
}





/* Dispays help for alias in various levels */
void help_cmd_alias(unsigned int level)
{
	printf("This is the %s help for '%s'.\n",
		level ? EXT_HELP : SHORT_HELP, cmdname);
	return;
}

/* Main entry point for alias, accepts an array of arguments */
int cmd_alias(char **argv)
{
	
	if (argv[0] == NULL) {
		list_aliases();
		return CMD_SUCCESS;
	}else if (argv[1] == NULL && strpos(argv[0], "=") == -1) {
		return print_alias(argv[0]);
	}


	char* str = (char*)malloc(INPUT_MAX * sizeof(char));
	str[0] = '\0';

	size_t i;
	for(i = 0; argv[i] != NULL; i++) {
		str = strcat(str, argv[i]);
	}

	
	
	set_alias(name, value);
	return CMD_SUCCESS;
}

