/*
 * SPDX-FileCopyrightText: 2022 Jiri Svoboda
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** @addtogroup libdisplay
 * @{
 */
/** @file
 */

#ifndef LIBDISPLAY_IPC_DISPLAY_H
#define LIBDISPLAY_IPC_DISPLAY_H

#include <ipc/common.h>

typedef enum {
	DISPLAY_CALLBACK_CREATE = IPC_FIRST_USER_METHOD,
	DISPLAY_WINDOW_CREATE,
	DISPLAY_WINDOW_DESTROY,
	DISPLAY_WINDOW_MAXIMIZE,
	DISPLAY_WINDOW_MOVE,
	DISPLAY_WINDOW_MOVE_REQ,
	DISPLAY_WINDOW_GET_POS,
	DISPLAY_WINDOW_GET_MAX_RECT,
	DISPLAY_WINDOW_RESIZE,
	DISPLAY_WINDOW_RESIZE_REQ,
	DISPLAY_WINDOW_SET_CURSOR,
	DISPLAY_WINDOW_UNMAXIMIZE,
	DISPLAY_GET_EVENT,
	DISPLAY_GET_INFO
} display_request_t;

typedef enum {
	DISPLAY_EV_PENDING = IPC_FIRST_USER_METHOD
} display_event_t;

#endif

/** @}
 */
