# Platform
PLATFORM = mips32

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Support for SMP
CONFIG_SMP = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y

# Keyboard layout
KBD_LAYOUT = us_qwerty
