/* This file is automatically generated by gencontext.c. */
/* struct context */
#define OFFSET_SP    0x0
#define OFFSET_PC    0x8
#define OFFSET_R2    0x10
#define OFFSET_R13   0x18
#define OFFSET_R14   0x20
#define OFFSET_R15   0x28
#define OFFSET_R16   0x30
#define OFFSET_R17   0x38
#define OFFSET_R18   0x40
#define OFFSET_R19   0x48
#define OFFSET_R20   0x50
#define OFFSET_R21   0x58
#define OFFSET_R22   0x60
#define OFFSET_R23   0x68
#define OFFSET_R24   0x70
#define OFFSET_R25   0x78
#define OFFSET_R26   0x80
#define OFFSET_R27   0x88
#define OFFSET_R28   0x90
#define OFFSET_R29   0x98
#define OFFSET_R30   0xa0
#define OFFSET_R31   0xa8
#define OFFSET_CR    0xb0

#define OFFSET_FR14  0x0
#define OFFSET_FR15  0x8
#define OFFSET_FR16  0x10
#define OFFSET_FR17  0x18
#define OFFSET_FR18  0x20
#define OFFSET_FR19  0x28
#define OFFSET_FR20  0x30
#define OFFSET_FR21  0x38
#define OFFSET_FR22  0x40
#define OFFSET_FR23  0x48
#define OFFSET_FR24  0x50
#define OFFSET_FR25  0x58
#define OFFSET_FR26  0x60
#define OFFSET_FR27  0x68
#define OFFSET_FR28  0x70
#define OFFSET_FR29  0x78
#define OFFSET_FR30  0x80
#define OFFSET_FR31  0x88
#define OFFSET_FPSCR 0x90

 /** @}
 */

