# Platform
PLATFORM = sparc64

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Support for SMP
CONFIG_SMP = y

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Use TSB
CONFIG_TSB = y

# Virtually indexed D-cache support
CONFIG_VIRT_IDX_DCACHE = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# Start AP processors by the loader
CONFIG_AP = y

# Preserve A.OUT header in isofs.b
CONFIG_AOUT_ISOFS_B = y

# External ramdisk
CONFIG_RD_EXTERNAL = y

# Keyboard layout
KBD_LAYOUT = us_qwerty
