/* Generated file. Edit errno.in instead. */
#define EOK                   0
#define ENOENT               -1
#define ENOMEM               -2
#define ELIMIT               -3
#define EREFUSED             -4
#define EFORWARD             -5
#define EPERM                -6
#define EHANGUP              -7
#define EPARTY               -8
#define EEXIST               -9
#define EBADMEM             -10
#define ENOTSUP             -11
#define EADDRNOTAVAIL       -12
#define ETIMEOUT            -13
#define EINVAL              -14
#define EBUSY               -15
#define EOVERFLOW           -16
#define EINTR               -17
#define EMFILE              -18
#define ENAMETOOLONG       -256
#define EISDIR             -257
#define ENOTDIR            -258
#define ENOSPC             -259
#define ENOTEMPTY          -261
#define EBADF              -262
#define EDOM               -263
#define ERANGE             -264
#define EXDEV              -265
#define EIO                -266
#define EMLINK             -267
#define ENXIO              -268
#define ENOFS              -269
#define EBADCHECKSUM       -300
#define ESTALL             -301
#define EEMPTY             -302
#define ENAK               -303
#define EAGAIN           -11002
