/*
 * SPDX-FileCopyrightText: 2005 Martin Decky
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** @addtogroup abi_generic
 * @{
 */
/** @file
 */

#ifndef _ABI_SYSCALL_H_
#define _ABI_SYSCALL_H_

/** System calls.
 *
 * If you are adding or removing syscalls, or changing the number of
 * their arguments, please update syscall description table
 * in @c uspace/app/trace/syscalls.c
 */
typedef enum {
	SYS_KIO = 0,

	SYS_THREAD_CREATE,
	SYS_THREAD_EXIT,
	SYS_THREAD_GET_ID,
	SYS_THREAD_USLEEP,
	SYS_THREAD_UDELAY,

	SYS_TASK_GET_ID,
	SYS_TASK_SET_NAME,
	SYS_TASK_KILL,
	SYS_TASK_EXIT,
	SYS_PROGRAM_SPAWN_LOADER,

	SYS_WAITQ_CREATE,
	SYS_WAITQ_SLEEP,
	SYS_WAITQ_WAKEUP,
	SYS_WAITQ_DESTROY,
	SYS_SMC_COHERENCE,

	SYS_AS_AREA_CREATE,
	SYS_AS_AREA_RESIZE,
	SYS_AS_AREA_CHANGE_FLAGS,
	SYS_AS_AREA_GET_INFO,
	SYS_AS_AREA_DESTROY,

	SYS_PAGE_FIND_MAPPING,

	SYS_IPC_CALL_ASYNC_FAST,
	SYS_IPC_CALL_ASYNC_SLOW,
	SYS_IPC_ANSWER_FAST,
	SYS_IPC_ANSWER_SLOW,
	SYS_IPC_FORWARD_FAST,
	SYS_IPC_FORWARD_SLOW,
	SYS_IPC_WAIT,
	SYS_IPC_POKE,
	SYS_IPC_HANGUP,
	SYS_IPC_CONNECT_KBOX,

	SYS_IPC_EVENT_SUBSCRIBE,
	SYS_IPC_EVENT_UNSUBSCRIBE,
	SYS_IPC_EVENT_UNMASK,

	SYS_PERM_GRANT,
	SYS_PERM_REVOKE,

	SYS_PHYSMEM_MAP,
	SYS_PHYSMEM_UNMAP,
	SYS_DMAMEM_MAP,
	SYS_DMAMEM_UNMAP,
	SYS_IOSPACE_ENABLE,
	SYS_IOSPACE_DISABLE,

	SYS_IPC_IRQ_SUBSCRIBE,
	SYS_IPC_IRQ_UNSUBSCRIBE,

	SYS_SYSINFO_GET_KEYS_SIZE,
	SYS_SYSINFO_GET_KEYS,
	SYS_SYSINFO_GET_VAL_TYPE,
	SYS_SYSINFO_GET_VALUE,
	SYS_SYSINFO_GET_DATA_SIZE,
	SYS_SYSINFO_GET_DATA,

	SYS_DEBUG_CONSOLE,

	SYS_KLOG
} syscall_t;

#endif

/** @}
 */
