#!/bin/bash
#
# SPDX-FileCopyrightText: 2014 Vojtech Horky
#
# SPDX-License-Identifier: BSD-3-Clause
#

# FIXME: update for meson config

run_echo() {
	echo "[exec]:" "$@"
	"$@"
}

RUN=run_echo


# Because of the very first command we issue that deletes about everything
if ! [ "$1" == "really-overwrite" ]; then
	echo "Wrong argument, see sources!"
	exit 1
fi

$RUN find -not -name update-from-master.sh -and -not -name doc -and -not -name 'doxygroups.h' -delete
$RUN wget -q https://github.com/vhotspur/pcut/archive/master.zip -O pcut-master.zip
$RUN unzip -q -u pcut-master.zip
$RUN mv -f pcut-master/src .
$RUN mv -f pcut-master/include .
$RUN mv -f pcut-master/tests .
$RUN mv -f pcut-master/helenos*.mak .
$RUN rm -rf pcut-master pcut-master.zip
$RUN rm -f CMakeLists.txt *.cmake run_test.sh

cat >Makefile <<'EOF_MAKEFILE_HEAD'
#
# This file was generated by call to update-from-master.sh
#

USPACE_PREFIX = ../..
PCUT_TEST_PREFIX = test-libpcut-

SELF_TESTS = \
EOF_MAKEFILE_HEAD

for testfile in tests/*.expected; do
	testname=`basename "$testfile" .expected`
	echo "	\$(PCUT_TEST_PREFIX)${testname}\$(PCUT_TEST_SUFFIX) \\"
done | sed '$s/\\$//' >>Makefile

cat >>Makefile <<'EOF_MAKEFILE_TAIL'

EXTRA_CLEAN = $(SELF_TESTS)

include helenos.mak

include $(USPACE_PREFIX)/Makefile.common

include helenos.test.mak

all-test: $(SELF_TESTS)

test-libpcut-%: $(LIBRARY).a
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(START_FILES) $^ $(LIBRARY).a $(BASE_LIBS)

EOF_MAKEFILE_TAIL
