# Platform
PLATFORM = amd64

# CPU type
MACHINE = opteron

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for SMP
CONFIG_SMP = y

# Improved support for hyperthreading
CONFIG_HT = y

# Simics BIOS AP boot fix
CONFIG_SIMICS_FIX = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Watchpoint on rewriting AS with zero
CONFIG_DEBUG_AS_WATCHPOINT = y

# Save all interrupt registers
CONFIG_DEBUG_ALLREGS = y

# Compile kernel tests
CONFIG_TEST = y

# Framebuffer support
CONFIG_FB = y

# Framebuffer width
CONFIG_VESA_WIDTH = 1024

# Framebuffer height
CONFIG_VESA_HEIGHT = 768

# Framebuffer depth
CONFIG_VESA_BPP = 24
