# Platform
PLATFORM = ia64

# Ramdisk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# In case compiler is clang, whether or not to use its integrated assembler.
INTEGRATED_AS = default

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Support for SMP
CONFIG_SMP = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Use VHPT
CONFIG_VHPT = n

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# Optimization level
OPTIMIZATION = 2
