# Machine type
MACHINE = beagleboardxm

# RAM disk format
RDFMT = ext4fs

#framebuffer
CONFIG_FB = y

CONFIG_BFB_MODE = 1024x768
CONFIG_BFB_BPP = 24

# Barebone build with essential binaries only
CONFIG_BAREBONE = y
