/* Automatically generated by mknewcmd on Fre Nov 30 05:45:31 CET 2018
 * This is machine generated output. The author of mknewcmd claims no
 * copyright over the contents of this file. Where legally permitted, the
 * contents herein are donated to the public domain.
 *
 * You should apply any license and copyright that you wish to this file,
 * replacing this header in its entirety. */

#include <stdio.h>
#include <stdlib.h>
#include <adt/odict.h>

#include "config.h"
#include "util.h"
#include "errors.h"
#include "entry.h"
#include "unalias.h"
#include "cmds.h"



static const char *cmdname = "unalias";

/* Dispays help for unalias in various levels */
void help_cmd_unalias(unsigned int level)
{
	printf("This is the %s help for '%s'.\n",
		level ? EXT_HELP : SHORT_HELP, cmdname);
	return;
}

/* Main entry point for unalias, accepts an array of arguments */
int cmd_unalias(char **argv)
{

	size_t i;

	for(i = 1; argv[i] != NULL; i++) {
		odlink_t *alias_link = odict_find_eq(&alias_dict, (void*)argv[i], NULL);

		if(alias_link == NULL) {
			printf("%s: No alias '%s' found\n", cmdname, argv[i]);
			return CMD_FAILURE;
		}

		alias_t *data = odict_get_instance(alias_link, alias_t, odict);
		odict_remove(alias_link);

		free(data->name);
		free(data->value);
		free(data);
	}

	
	
	return CMD_SUCCESS;
}

