# RAM disk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Support for SMP
CONFIG_SMP = y

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Load disk drivers on startup
CONFIG_START_BD = n

