# RAM disk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# In case compiler is clang, whether or not to use its integrated assembler.
INTEGRATED_AS = default

# Support for SMP
CONFIG_SMP = y

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Optimization level
OPTIMIZATION = 3
