
/*****************************************************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/autogen.py
 * Generated from: arch/amd64/include/libarch/fibril_context.ag
 *****************************************************************************/

#ifndef AUTOGEN_CONTEXT_H
#define AUTOGEN_CONTEXT_H

#ifndef __ASM__
#include <stddef.h>
#include <stdint.h>
#endif

#define CONTEXT_OFFSET_SP 0
#define CONTEXT_SIZE_SP 8
#define CONTEXT_OFFSET_PC 8
#define CONTEXT_SIZE_PC 8
#define CONTEXT_OFFSET_RBX 16
#define CONTEXT_SIZE_RBX 8
#define CONTEXT_OFFSET_RBP 24
#define CONTEXT_SIZE_RBP 8
#define CONTEXT_OFFSET_R12 32
#define CONTEXT_SIZE_R12 8
#define CONTEXT_OFFSET_R13 40
#define CONTEXT_SIZE_R13 8
#define CONTEXT_OFFSET_R14 48
#define CONTEXT_SIZE_R14 8
#define CONTEXT_OFFSET_R15 56
#define CONTEXT_SIZE_R15 8
#define CONTEXT_OFFSET_TLS 64
#define CONTEXT_SIZE_TLS 8
#define CONTEXT_SIZE 72

#ifndef __ASM__
typedef struct context {
	uint64_t sp;
	uint64_t pc;
	uint64_t rbx;
	uint64_t rbp;
	uint64_t r12;
	uint64_t r13;
	uint64_t r14;
	uint64_t r15;
	uint64_t tls;
} context_t;
#endif

#endif
	
