
/*****************************************************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!!
 * Generated by: tools/autogen.py
 * Generated from: arch/amd64/include/libarch/istate_struct.ag
 *****************************************************************************/

#ifndef AUTOGEN_ISTATE_H
#define AUTOGEN_ISTATE_H

#ifndef __ASM__
#ifdef KERNEL
#include <typedefs.h>
#endif
#ifndef KERNEL
#include <stddef.h>
#endif
#ifndef KERNEL
#include <stdint.h>
#endif
#endif

#define ISTATE_OFFSET_RAX 0
#define ISTATE_SIZE_RAX 8
#define ISTATE_OFFSET_RBX 8
#define ISTATE_SIZE_RBX 8
#define ISTATE_OFFSET_RCX 16
#define ISTATE_SIZE_RCX 8
#define ISTATE_OFFSET_RDX 24
#define ISTATE_SIZE_RDX 8
#define ISTATE_OFFSET_RSI 32
#define ISTATE_SIZE_RSI 8
#define ISTATE_OFFSET_RDI 40
#define ISTATE_SIZE_RDI 8
#define ISTATE_OFFSET_RBP 48
#define ISTATE_SIZE_RBP 8
#define ISTATE_OFFSET_R8 56
#define ISTATE_SIZE_R8 8
#define ISTATE_OFFSET_R9 64
#define ISTATE_SIZE_R9 8
#define ISTATE_OFFSET_R10 72
#define ISTATE_SIZE_R10 8
#define ISTATE_OFFSET_R11 80
#define ISTATE_SIZE_R11 8
#define ISTATE_OFFSET_R12 88
#define ISTATE_SIZE_R12 8
#define ISTATE_OFFSET_R13 96
#define ISTATE_SIZE_R13 8
#define ISTATE_OFFSET_R14 104
#define ISTATE_SIZE_R14 8
#define ISTATE_OFFSET_R15 112
#define ISTATE_SIZE_R15 8
#define ISTATE_OFFSET_ALIGNMENT 120
#define ISTATE_SIZE_ALIGNMENT 8
#define ISTATE_OFFSET_RBP_FRAME 128
#define ISTATE_SIZE_RBP_FRAME 8
#define ISTATE_OFFSET_RIP_FRAME 136
#define ISTATE_SIZE_RIP_FRAME 8
#define ISTATE_OFFSET_ERROR_WORD 144
#define ISTATE_SIZE_ERROR_WORD 8
#define ISTATE_OFFSET_RIP 152
#define ISTATE_SIZE_RIP 8
#define ISTATE_OFFSET_CS 160
#define ISTATE_SIZE_CS 8
#define ISTATE_OFFSET_RFLAGS 168
#define ISTATE_SIZE_RFLAGS 8
#define ISTATE_OFFSET_RSP 176
#define ISTATE_SIZE_RSP 8
#define ISTATE_OFFSET_SS 184
#define ISTATE_SIZE_SS 8
#define ISTATE_SIZE 192

#ifndef __ASM__
typedef struct istate {
	uint64_t rax;
	uint64_t rbx;
	uint64_t rcx;
	uint64_t rdx;
	uint64_t rsi;
	uint64_t rdi;
	uint64_t rbp;
	uint64_t r8;
	uint64_t r9;
	uint64_t r10;
	uint64_t r11;
	uint64_t r12;
	uint64_t r13;
	uint64_t r14;
	uint64_t r15;
	uint64_t alignment;
	uint64_t rbp_frame;
	uint64_t rip_frame;
	uint64_t error_word;
	uint64_t rip;
	uint64_t cs;
	uint64_t rflags;
	uint64_t rsp;
	uint64_t ss;
} istate_t;
#endif

#endif
	
