/* This file is automatically generated by gencontext.c. */
/* struct context */
#define OFFSET_SP      0x0
#define OFFSET_PC      0x4
#define OFFSET_S0      0x8
#define OFFSET_S1      0xc
#define OFFSET_S2      0x10
#define OFFSET_S3      0x14
#define OFFSET_S4      0x18
#define OFFSET_S5      0x1c
#define OFFSET_S6      0x20
#define OFFSET_S7      0x24
#define OFFSET_S8      0x28
#define OFFSET_GP      0x2c
#define OFFSET_TLS     0x30
