/* Automatically generated by mknewcmd on Wednesday 28 October 2020 05:35:04 PM
 * IST This is machine generated output. The author of mknewcmd claims no
 * copyright over the contents of this file. Where legally permitted, the
 * contents herein are donated to the public domain.
 *
 * You should apply any license and copyright that you wish to this file,
 * replacing this header in its entirety. */

#include "basename.h"
#include <mem.h>
#include <stdio.h>
#include <stdlib.h>
#include <str.h>
#include "cmds.h"
#include "config.h"
#include "entry.h"
#include "errors.h"
#include "util.h"

static const char *cmdname = "basename";

/* Dispays help for basename in various levels */
void help_cmd_basename(unsigned int level)
{
	printf("This is the %s help for '%s'.\n", level ? EXT_HELP : SHORT_HELP,
	    cmdname);
	return;
}

// function for getting file name from the given path.
static char *filename(char *path)
{
	char *base = str_rchr(path, '/');
	return base ? base + 1 : path;
}

/* Main entry point for basename, accepts an array of arguments */
int cmd_basename(char **argv)
{
	unsigned int argc;

	/* Count the arguments */
	for (argc = 0; argv[argc] != NULL; argc++)
		;

	// atleast 2 arguments must be passed to run the command
	if (argc < 2) {
		fprintf(stderr, "%s: expected argument\n", argv[0]);
		return CMD_FAILURE;
	}

	// extracting the file name from the given path
	char *c = filename(argv[1]);

	if (argc > 2) {
		char *suff = argv[2];
		char *result =
		    str_str(c + str_length(c) - str_length(suff), suff);
		if (result
		    && (result - c
		        == (int) (str_length(c) - str_length(suff)))) {
			*result = '\0';
		}
	}

	fprintf(stdout, "%s\n", c);

	return CMD_SUCCESS;
}
