# Platform
PLATFORM = arm32

# Ramdisk format
RDFMT = ext4fs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# What is your input device?
CONFIG_HID_IN = generic

# What is your output device?
CONFIG_HID_OUT = generic
