# Platform
PLATFORM = arm32

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y

# What is your input device?
CONFIG_HID_IN = keyboard

# What is your output device?
CONFIG_HID_OUT = monitor

# Framebuffer support
CONFIG_FB = y

# Keyboard layout
KBD_LAYOUT = us_qwerty
