# Platform
PLATFORM = amd64

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Support for SMP
CONFIG_SMP = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Kernel symbol information
CONFIG_SYMTAB = y

# Detailed kernel logging
CONFIG_LOG = n

# Kernel function tracing
CONFIG_TRACE = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# PC keyboard support
CONFIG_PC_KBD = y

# EGA support
CONFIG_EGA = y

# Framebuffer support
CONFIG_FB = y

# Default framebuffer mode
CONFIG_BFB_MODE = 800x600

# Default framebuffer depth
CONFIG_BFB_BPP = 16

# Load disk drivers on startup
CONFIG_START_BD = n

# Mount /data on startup
CONFIG_MOUNT_DATA = n

# OHCI root hub power switch, ganged is enough
OHCI_POWER_SWITCH = ganged

# GRUB boot loader architecture
GRUB_ARCH = pc
