# Platform
PLATFORM = amd64

# Ramdisk format
RDFMT = fat

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Support for SMP
CONFIG_SMP = y

# Improved support for hyperthreading
CONFIG_HT = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = y

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Compile kernel tests
CONFIG_TEST = y

# Input device class
CONFIG_HID_IN = generic

# Output device class
CONFIG_HID_OUT = generic

# PC keyboard support
CONFIG_PC_KBD = y

# EGA support
CONFIG_EGA = y

# Framebuffer support
CONFIG_FB = y

# Framebuffer width
CONFIG_VESA_WIDTH = 800

# Framebuffer height
CONFIG_VESA_HEIGHT = 600

# Framebuffer depth
CONFIG_VESA_BPP = 16

# Keyboard layout
KBD_LAYOUT = us_qwerty
