# Platform
PLATFORM = ia32xen

# CPU type
MACHINE = pentium4

# Ramdisk format
RDFMT = tmpfs

# Compiler
COMPILER = gcc_cross

# Debug build
CONFIG_DEBUG = y

# Support for SMP
CONFIG_SMP = y

# Improved support for hyperthreading
CONFIG_HT = y

# Lazy FPU context switching
CONFIG_FPU_LAZY = y

# Support for userspace debuggers
CONFIG_UDEBUG = n

# Kernel console support
CONFIG_KCONSOLE = y

# Detailed kernel logging
CONFIG_LOG = n

# Deadlock detection support for spinlocks
CONFIG_DEBUG_SPINLOCK = y

# Watchpoint on rewriting AS with zero
CONFIG_DEBUG_AS_WATCHPOINT = y

# Save all interrupt registers
CONFIG_DEBUG_ALLREGS = y

# Compile kernel tests
CONFIG_TEST = y
