/* This file is automatically generated by gencontext.c. */
/* struct context */
#define OFFSET_O1  0x0
#define OFFSET_O2  0x8
#define OFFSET_O3  0x10
#define OFFSET_O4  0x18
#define OFFSET_O5  0x20
#define OFFSET_SP  0x28
#define OFFSET_PC  0x30
