/* This file is automatically generated by gencontext.c. */
/* struct context */
#define OFFSET_SP  0x38
#define OFFSET_FP  0x28
#define OFFSET_PC  0x30
#define OFFSET_I1  0x0
#define OFFSET_I2  0x8
#define OFFSET_I3  0x10
#define OFFSET_I4  0x18
#define OFFSET_I5  0x20
