/* This file is automatically generated by gencontext.c. */
/* struct context */
#define OFFSET_SP  0x68
#define OFFSET_PC  0x70
#define OFFSET_L0  0x0
#define OFFSET_L1  0x8
#define OFFSET_L2  0x10
#define OFFSET_L3  0x18
#define OFFSET_L4  0x20
#define OFFSET_L5  0x28
#define OFFSET_L6  0x30
#define OFFSET_L7  0x38
#define OFFSET_I1  0x40
#define OFFSET_I2  0x48
#define OFFSET_I3  0x50
#define OFFSET_I4  0x58
#define OFFSET_I5  0x60
