/*
 * SPDX-FileCopyrightText: 2010 Vojtech Horky
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/** @addtogroup libusbhid
 * @{
 */
/** @file
 * @brief USB HID Usage Tables.
 */
#ifndef LIBUSBHID_HIDUT_H_
#define LIBUSBHID_HIDUT_H_

/** USB/HID Usage Pages. */
typedef enum {
	USB_HIDUT_PAGE_GENERIC_DESKTOP = 1,
	USB_HIDUT_PAGE_SIMULATION = 2,
	USB_HIDUT_PAGE_VR = 3,
	USB_HIDUT_PAGE_SPORT = 4,
	USB_HIDUT_PAGE_GAME = 5,
	USB_HIDUT_PAGE_GENERIC_DEVICE = 6,
	USB_HIDUT_PAGE_KEYBOARD = 7,
	USB_HIDUT_PAGE_LED = 8,
	USB_HIDUT_PAGE_BUTTON = 9,
	USB_HIDUT_PAGE_ORDINAL = 0x0a,
	USB_HIDUT_PAGE_TELEPHONY_DEVICE = 0x0b,
	USB_HIDUT_PAGE_CONSUMER = 0x0c
} usb_hidut_usage_page_t;

/** Usages for Generic Desktop Page. */
typedef enum {
	USB_HIDUT_USAGE_GENERIC_DESKTOP_POINTER = 1,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_MOUSE = 2,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_JOYSTICK = 4,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_GAMEPAD = 5,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_KEYBOARD = 6,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_KEYPAD = 7,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_X = 0x30,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_Y = 0x31,
	USB_HIDUT_USAGE_GENERIC_DESKTOP_WHEEL = 0x38
	/* USB_HIDUT_USAGE_GENERIC_DESKTOP_ = , */

} usb_hidut_usage_generic_desktop_t;

typedef enum {
	USB_HIDUT_USAGE_CONSUMER_CONSUMER_CONTROL = 1
} usb_hidut_usage_consumer_t;

#endif
/**
 * @}
 */
