#! /bin/sh
ARCH=$1
TAG="`svnversion . 2> /dev/null`"
TIMESTAMP="`date "+%Y-%m-%d %H:%M:%S" 2> /dev/null`"
if [ -z "$TAG" ] || [ "$TAG" == "exported" ]; then
	TAG="Built on $TIMESTAMP for $ARCH"
else
	TAG="Revision $TAG (built on $TIMESTAMP for $ARCH)"
fi
echo $TAG
