#! /bin/sh

function syntax {
	echo "Syntax:"
	echo " build.<arch> [-compiler <compiler>]"
	echo
	echo "<arch>     ... ia32, mips32, mips32el"
	echo "<compiler> ... native, *cross"
	echo
}

ARCH="`basename "$0" | awk -F. '{ if (NF > 1) print \$NF }'`"
if [ -z "$ARCH" ]; then
	syntax
	exit 1
fi

ARGS="ARCH=$ARCH"
while [ "$#" -gt 0 ]; do
	case "$1" in
		-compiler)
			if [ -z "$2" ]; then
				syntax
				exit 1
			fi
			ARGS="$ARGS COMPILER=$2"
			shift
			;;
		*)
			syntax
			exit 1
			;;
	esac
	shift
done

make all $ARGS
