#ARCH=ia32
#ARCH=mips
#ARCH=ia64
#ARCH=ppc
#ARCH=amd64

# Support for symetric multiprocessors
#SMP=__SMP__

# Improved support for hyperthreading
HT=__HT__

# General debuging and assert checking disable
#NDEBUG=__NDEBUG__

# Deadlock detection support for spinlocks.
DEBUG_SPINLOCK=DEBUG_SPINLOCK

# Uncomment if you want to compile in userspace support
#USERSPACE=__USERSPACE__

# Uncomment if you want to run in the test mode
#TEST=__TEST__

TEST_FILE=test.c

# Select what test do you want to run
#TEST_DIR=synch/rwlock1/
#TEST_DIR=synch/rwlock2/
#TEST_DIR=synch/rwlock3/
#TEST_DIR=synch/rwlock4/
#TEST_DIR=synch/rwlock5/
#TEST_DIR=synch/semaphore1/
#TEST_DIR=synch/semaphore2/
#TEST_DIR=fpu/fpu1
#TEST_DIR=print/print1
#TEST_DIR=thread/thread1
